### ISSUE TITLE
为什么你的文件都是js而不是tsx呢？

### ISSUE THREAD

**Issue by Hhpon** [jimczj/taro_zhihu#4]

**Comment by jimczj** [comment]
可以选择用不用typescript，这份代码没用

**Comment by Hhpon** [comment]
用不用这个的区别在哪呢？我看你的那个代码我改成tsx的时候会有编译器的报错。

**Comment by jimczj** [comment]
typescript 的语法跟 js语法有些差异，你自己可以去查下typescript的文档
